### PR TITLE
ES6 syntax

### PR DESCRIPTION
**Pull request by aminya**
## Description
- Use ES6 syntax in the source code
- Fix removeOldMap
- Fix babel compilation

## Why
You should use ES6 syntax in your library. You supply babeled code, so you don't need to stikc to the old syntax in the source code.

- declarations.block-scope: Transform `var` into `let` and `const` as 
appropriate.
- functions.arrow         : Transform regular functions to arrow 
functions as appropriate.
- objects.concise         : Use concise object property method syntax.
- objects.destructuring   : Transform some declarations and assignments 
to the more compact destructuring form.
- objects.shorthand       : Use shorthand notation for object 
properties.
- strings.template        : Transforms manual string concatenation into 
template strings.

```ps1
❯ npm install -g esnext
❯ $all= (ls -r )
foreach($obj in $all) {
	if ($obj.extension -eq '.js') {
		  $file = $obj.fullname
		  esnext -o $file $file -b modules.commonjs
	 }
}
```

### CODE REVIEW

**Comment by StefansArya** [comment]
Hi! Thanks for the contribution.
Currently I have something to do outside, I will view the changed code when I'm home 😄

**Comment by StefansArya** [comment]
Thanks! Looks like using `let` doesn't create a new function scope anymore when not needed.

On my experiment there are some feature on ES6 like `.forEach()` that was [slower](https://jsbench.me/mjkf8vjtfi/1) than the regular `for(loop)`. I think it's because JavaScript always calling the callback passed on `.forEach()` on each loop, and it's hard to be optimized for babel or the engine because the object prototype can different (like `forEach` was replaced with custom function).

That's why I still stick with old syntax and optimize some code from the ground.
I will consider to use `let` and `const` more often, Thanks!

**Comment by aminya** [comment]
You're welcome. Consider changing to ES6 modules as well. People want to tree shake libraries. A large library is not well accepted these days.

> On my experiment there are some feature on ES6 like .forEach() that was slower than the regular for(loop). I think it's because JavaScript always calling the callback passed on .forEach() on each loop, and it's hard to be optimized for babel or the engine because the object prototype can different (like forEach was replaced with custom function).

forEach has been always slower. Avoid functional programming. 
https://github.com/aminya/typescript-optimization#summary

**Comment by StefansArya** [comment]
Sure, I also think it would be more better.
After I didn't find another bug on some feature I will try to migrate it to ES6 modules.

**Pull request merged**
